//! This module orchestrates the fuzzing process using the `libafl` fuzzing framework.
//!
//! It defines the [`FuzzerOrchestrator`] trait, which provides a generic interface
//! for setting up and running fuzz tests against IC canisters. The main [`FuzzerOrchestrator::run`]
//! function configures and starts the `libafl` fuzzing loop, while
//! [`FuzzerOrchestrator::test_one_input`] provides a convenient way to debug specific inputs.
//!
//! When [`FuzzerOrchestrator::instruction_config`] returns an [`InstructionConfig`] with
//! `enabled: true`, the fuzzer additionally tracks instruction counts via
//! [`set_instruction_count`](FuzzerOrchestrator::set_instruction_count) and uses
//! [`InstructionCountFeedback`](crate::custom::feedback::instruction_count::InstructionCountFeedback)
//! to guide inputs toward higher instruction consumption. Setting `debug: true` prints
//! the new maximum to stdout each time the record is broken.

use candid::Principal;
use chrono::Local;
use ic_management_canister_types::CanisterId;
use libafl::feedback_or;
use libafl::feedbacks::{ExitKindFeedback, TimeoutFeedback};
use pocket_ic::PocketIc;
use std::fs::{self, File};
use std::io::Read;
use std::path::PathBuf;
use std::sync::Arc;

use crate::custom::feedback::oom_exit_kind::OomLogic;
use crate::custom::mutator::candid::{CandidParserMutator, CandidTypeDefArgs};
use crate::libafl::{
    Evaluator,
    corpus::CachedOnDiskCorpus,
    events::SimpleEventManager,
    executors::{ExitKind, inprocess::InProcessExecutor},
    feedbacks::{CrashFeedback, map::AflMapFeedback},
    fuzzer::{Fuzzer, StdFuzzer},
    inputs::BytesInput,
    mutators::{HavocScheduledMutator, havoc_mutations},
    observers::map::{StdMapObserver, hitcount_map::HitcountsMapObserver},
    schedulers::QueueScheduler,
    stages::{AflStatsStage, CalibrationStage, mutational::StdMutationalStage},
    state::StdState,
};

use crate::libafl::monitors::SimpleMonitor;
// use libafl::monitors::tui::{ui::TuiUI, TuiMonitor};
use crate::libafl_bolts::{current_nanos, rands::StdRand, tuples::tuple_list};

use crate::constants::{COVERAGE_FN_EXPORT_NAME, INSTRUCTION_COUNT_FN_EXPORT_NAME};
use crate::custom::observer::instruction_count::INSTRUCTION_MAP;
use crate::fuzzer::FuzzerState;

/// Configuration for instruction count maximization.
///
/// Returned by [`FuzzerOrchestrator::instruction_config`]. When `enabled` is true,
/// the fuzzer tracks instruction counts and considers inputs that increase the maximum
/// as "interesting".
#[derive(Debug, Clone, Default)]
pub struct InstructionConfig {
    /// Enable instruction count maximization feedback.
    pub enabled: bool,
    /// Print the new maximum instruction count to stdout each time the record is broken.
    pub debug: bool,
}

/// A trait that defines the necessary components for a canister fuzzing target.
///
/// Implementors of this trait provide the specific logic for setting up the environment,
/// executing a test case against one or more canisters, and cleaning up afterwards.
pub trait FuzzerOrchestrator: AsRef<FuzzerState> + AsMut<FuzzerState> {
    /// Performs one-time initialization at the start of the fuzzing campaign.
    /// This is where canisters are typically installed.
    fn init(&mut self);

    /// Sets up the environment before each execution of a test case.
    /// This could involve resetting canister state to a clean snapshot.
    fn setup(&self) {}

    /// Executes a single fuzzing input against the target canister(s).
    ///
    /// # Arguments
    ///
    /// * `input` - The `BytesInput` generated by the fuzzer.
    ///
    /// # Returns
    ///
    /// * `ExitKind` - Indicates the outcome of the execution (e.g., `Ok`, `Crash`).
    fn execute(&self, input: BytesInput) -> ExitKind;

    /// Returns a thread-safe reference to the `PocketIc` instance.
    fn get_state_machine(&self) -> Arc<PocketIc> {
        self.as_ref().get_state_machine()
    }

    /// Returns the `CanisterId` of the canister that has been instrumented for coverage.
    fn get_coverage_canister_id(&self) -> CanisterId {
        self.as_ref().get_coverage_canister_id()
    }

    /// Creates and returns the path to a new timestamped directory for storing input items.
    ///
    /// The directory is structured as `$OUT_DIR/artifacts/<fuzzer_name>/<timestamp>/input`,
    /// where `$OUT_DIR` is the build script output directory (e.g., `target/debug/build/.../out`),
    /// `<fuzzer_name>` is the name provided to `FuzzerState::new`, and `<timestamp>` is based
    /// on the current time.
    ///
    /// # Panics
    ///
    /// Panics if the `OUT_DIR` environment variable is not set or if the directory cannot be created.
    fn input_dir(&self) -> PathBuf {
        let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is not set");
        let input_dir = PathBuf::from(out_dir)
            .join("artifacts")
            .join(self.as_ref().name())
            .join(Local::now().format("%Y%m%d_%H%M").to_string())
            .join("input");
        fs::create_dir_all(&input_dir)
            .unwrap_or_else(|e| panic!("Failed to create input directory {input_dir:?}: {e}"));
        println!("Input directory: {input_dir:?}");
        input_dir
    }

    /// Creates and returns the path to a new timestamped directory for storing crashes.
    ///
    /// The directory is structured as `$OUT_DIR/artifacts/<fuzzer_name>/<timestamp>/crashes`,
    /// where `$OUT_DIR` is the build script output directory (e.g., `target/debug/build/.../out`),
    /// `<fuzzer_name>` is the name provided to `FuzzerState::new`, and `<timestamp>` is based
    /// on the current time.
    ///
    /// # Panics
    ///
    /// Panics if the `OUT_DIR` environment variable is not set or if the directory cannot be created.
    fn crashes_dir(&self) -> PathBuf {
        let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is not set");
        let crashes_dir = PathBuf::from(out_dir)
            .join("artifacts")
            .join(self.as_ref().name())
            .join(Local::now().format("%Y%m%d_%H%M").to_string())
            .join("crashes");
        fs::create_dir_all(&crashes_dir)
            .unwrap_or_else(|e| panic!("Failed to create crashes directory {crashes_dir:?}: {e}"));
        println!("Crashes directory: {crashes_dir:?}");
        crashes_dir
    }

    /// Returns the path to the seed corpus directory.
    ///
    /// This directory should contain initial valid inputs to kickstart the fuzzing process.
    fn corpus_dir(&self) -> PathBuf;

    /// Fetches the coverage map from the instrumented canister and updates the global `COVERAGE_MAP`.
    ///
    /// It makes a update call to the `__export_coverage_for_afl` function on the coverage canister.
    /// If the update fails, the coverage map is not updated.
    #[allow(static_mut_refs)]
    fn set_coverage_map(&self) {
        let test = self.get_state_machine();
        let result = test.update_call(
            self.get_coverage_canister_id(),
            Principal::anonymous(),
            COVERAGE_FN_EXPORT_NAME,
            vec![],
        );
        if let Ok(result) = result {
            unsafe { crate::instrumentation::COVERAGE_MAP.copy_from_slice(&result) };
        }
    }

    /// Provides a mutable reference to the global `COVERAGE_MAP`.
    fn get_coverage_map(&self) -> &'static mut [u8] {
        unsafe { crate::instrumentation::COVERAGE_MAP }
    }

    /// Provides configuration for the `CandidParserMutator`.
    ///
    /// By default, this returns `None`, which disables the Candid-aware mutator.
    /// To enable it, override this method in your fuzzer implementation to return
    /// `Some(CandidTypeDefArgs { ... })`. You will need to provide the path to the
    /// `.did` file and the name of the canister method you intend to fuzz.
    ///
    /// This allows the fuzzer to perform structure-aware mutations on Candid-encoded inputs.
    fn get_candid_args() -> Option<CandidTypeDefArgs> {
        None
    }

    /// Returns configuration for instruction count maximization.
    ///
    /// Override this to return an [`InstructionConfig`] with `enabled: true` to track
    /// instruction counts and guide the fuzzer toward inputs that consume more IC instructions.
    /// Requires `instrument_instruction_count: true` in `InstrumentationArgs`.
    fn instruction_config() -> InstructionConfig {
        InstructionConfig::default()
    }

    /// Fetches the instruction count from the instrumented canister and updates the global `INSTRUCTION_MAP`.
    ///
    /// It makes an update call to the `__export_instruction_count_for_afl` function on the coverage canister.
    /// If the instruction count exceeds the previous maximum, the input is marked as interesting.
    #[allow(static_mut_refs)]
    fn set_instruction_count(&self) {
        let test = self.get_state_machine();
        let result = test.update_call(
            self.get_coverage_canister_id(),
            Principal::anonymous(),
            INSTRUCTION_COUNT_FN_EXPORT_NAME,
            vec![],
        );
        if let Ok(result) = result
            && result.len() >= 8
        {
            let instructions = u64::from_le_bytes(result[0..8].try_into().unwrap());
            let mut map = unsafe { INSTRUCTION_MAP.borrow_mut() };
            if instructions > map.max_instructions {
                map.increased = true;
                map.max_instructions = instructions;
                if Self::instruction_config().debug {
                    println!("[instructions] new max: {instructions}");
                }
            } else {
                map.increased = false;
            }
            map.current_instructions = instructions;
        }
    }

    /// The main entry point for running a fuzzing campaign.
    ///
    /// This function orchestrates the entire fuzzing process:
    /// 1. Calls `self.init()` for one-time setup.
    /// 2. Defines a `harness` closure that wraps `self.execute()` and updates the coverage map
    ///    (and optionally the instruction count).
    /// 3. Sets up `libafl` components:
    ///    - A `HitcountsMapObserver` to monitor the `COVERAGE_MAP`.
    ///    - `AflMapFeedback` for coverage-guided feedback and `CrashFeedback` for finding crashes.
    ///    - Optionally, `InstructionCountObserver` and `InstructionCountFeedback` when
    ///      [`instruction_config`](Self::instruction_config) has `enabled: true`.
    ///    - A `StdState` to hold the fuzzer's state (corpus, solutions, etc.).
    ///    - A `SimpleEventManager` with a `SimpleMonitor` for logging.
    ///    - A `QueueScheduler` to decide which input to fuzz next.
    ///    - An `InProcessExecutor` to run the harness.
    /// 4. Loads the initial seed corpus from the directory provided by `corpus_dir()`.
    /// 5. Configures mutational stages, including a `HavocScheduledMutator`.
    /// 6. Starts the main fuzzing loop.
    #[allow(static_mut_refs)]
    fn run(&mut self) {
        self.init();

        let inst_config = Self::instruction_config();

        let mut harness = |input: &BytesInput| {
            self.setup();
            let result = self.execute(input.clone());
            self.set_coverage_map();
            if inst_config.enabled {
                self.set_instruction_count();
            }
            result
        };

        let hitcount_map_observer = HitcountsMapObserver::new(unsafe {
            StdMapObserver::new("coverage_map", self.get_coverage_map())
        });

        // AflMapFeedback must be created before the observer is moved into a tuple.
        let afl_map_feedback = AflMapFeedback::new(&hitcount_map_observer);

        // The observer/feedback types differ at compile time depending on whether
        // instruction maximization is enabled, so we branch into the macro here.
        if inst_config.enabled {
            use crate::custom::feedback::instruction_count::InstructionCountFeedback;
            use crate::custom::observer::instruction_count::INSTRUCTION_COUNT_OBSERVER_NAME;
            use crate::libafl::observers::RefCellValueObserver;
            use crate::libafl_bolts::ownedref::OwnedRef;
            use std::ptr::addr_of;

            let instruction_count_observer = unsafe {
                RefCellValueObserver::new(
                    INSTRUCTION_COUNT_OBSERVER_NAME,
                    OwnedRef::from_ptr(addr_of!(INSTRUCTION_MAP)),
                )
            };

            let feedback = feedback_or!(InstructionCountFeedback::new(), afl_map_feedback.clone());
            run_fuzzing_loop!(
                self,
                &mut harness,
                tuple_list!(hitcount_map_observer, instruction_count_observer),
                afl_map_feedback,
                feedback
            );
        } else {
            let feedback = afl_map_feedback.clone();
            run_fuzzing_loop!(
                self,
                &mut harness,
                tuple_list!(hitcount_map_observer),
                afl_map_feedback,
                feedback
            );
        }
    }

    /// Executes a single input against the orchestrator's harness.
    ///
    /// This function is useful for debugging specific inputs, such as those that
    /// have caused a crash, without running the full fuzzing loop. It calls
    /// `init`, `setup`, `execute` in sequence for the given input.
    ///
    /// # Arguments
    ///
    /// * `bytes` - The raw byte vector of the input to be tested.
    fn test_one_input(&mut self, bytes: Vec<u8>) {
        self.init();
        self.setup();
        let result = self.execute(BytesInput::new(bytes));
        println!("Execution result: {result:?}");
    }
}

/// Macro to avoid duplicating the fuzzing loop for different observer/feedback
/// type tuples. The observer tuple and feedback composition differ depending on whether
/// instruction maximization is enabled, but the rest of the loop (state, executor,
/// corpus loading, stages) is identical.
///
/// `$afl_map_feedback` must be an already-constructed `AflMapFeedback` (created from
/// the hitcount observer before the observer is moved into the tuple).
#[macro_export]
macro_rules! run_fuzzing_loop {
    ($self:expr, $harness:expr, $observers:expr, $afl_map_feedback:expr, $feedback:expr) => {{
        let afl_map_feedback = $afl_map_feedback;
        let mut feedback = $feedback;
        let calibration_stage = CalibrationStage::new(&afl_map_feedback);

        let crash_feedback = CrashFeedback::new();
        let timeout_feedback = TimeoutFeedback::new();
        let oom_feedback: ExitKindFeedback<OomLogic> = ExitKindFeedback::new();
        let mut objective = feedback_or!(crash_feedback, timeout_feedback, oom_feedback);

        let stats_stage = AflStatsStage::builder()
            .map_feedback(&afl_map_feedback)
            .build()
            .unwrap();

        let mut state = StdState::new(
            StdRand::with_seed(current_nanos()),
            CachedOnDiskCorpus::new($self.input_dir(), 512).unwrap(),
            CachedOnDiskCorpus::new($self.crashes_dir(), 512).unwrap(),
            &mut feedback,
            &mut objective,
        )
        .unwrap();

        let mon = SimpleMonitor::new(|s| println!("{s}"));
        let mut mgr = SimpleEventManager::new(mon);
        let scheduler = QueueScheduler::new();
        let mut fuzzer = StdFuzzer::new(scheduler, feedback, objective);

        let mut executor =
            InProcessExecutor::new($harness, $observers, &mut fuzzer, &mut state, &mut mgr)
                .expect("Failed to create the Executor");

        // Load initial inputs from the corpus directory
        let paths = fs::read_dir($self.corpus_dir()).unwrap();
        for path in paths {
            let p = path.unwrap().path();
            let mut f = File::open(p.clone()).unwrap();
            let mut buffer = Vec::new();
            f.read_to_end(&mut buffer).unwrap();
            fuzzer
                .evaluate_input(
                    &mut state,
                    &mut executor,
                    &mut mgr,
                    &BytesInput::new(buffer),
                )
                .unwrap();
        }

        let mutator = HavocScheduledMutator::new(havoc_mutations());
        let mut stages = tuple_list!(
            calibration_stage,
            StdMutationalStage::transforming(CandidParserMutator::new(Self::get_candid_args())),
            StdMutationalStage::transforming(mutator),
            stats_stage
        );

        fuzzer
            .fuzz_loop(&mut stages, &mut executor, &mut state, &mut mgr)
            .expect("Error in the fuzzing loop");
    }};
}
// Required for the macro to be usable within trait methods above.
use run_fuzzing_loop;
